# Generated by Django 4.0.4 on 2022-04-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamo_blogger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('published', 'published'), ('in-review', 'in-review'), ('rejected', 'rejected')], default='draft', max_length=10),
        ),
    ]
