# Generated by Django 3.2.10 on 2022-04-17 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynamo_blogger', '0002_alter_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dynamo_blogger.timestampedmodel')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Blog Newsletters',
                'db_table': 'blog_newsletters',
            },
            bases=('dynamo_blogger.timestampedmodel',),
        ),
    ]
