# Generated by Django 3.2.10 on 2022-04-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamo_blogger', '0002_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='dynamo_blogger.Category'),
        ),
        migrations.AddField(
            model_name='post',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
