# Generated by Django 3.2.10 on 2022-04-16 21:39

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dynamo_blogger', '0007_alter_post_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAuthor',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dynamo_blogger.timestampedmodel')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='author_images/')),
                ('biography', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Blog Authors',
                'db_table': 'blog_authors',
            },
            bases=('dynamo_blogger.timestampedmodel',),
        ),
    ]
